version: "3.8"

services:
  portainer:
    image: portainer/portainer-ce:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/md0/volumes/portainer/data:/data
    labels:
      - traefik.enable=true
      - traefik.http.routers.portainer.rule=Host(`portainer.rileymathews.com`)
      - traefik.http.routers.portainer.tls.certresolver=le
      - traefik.http.services.portainer-portainer.loadbalancer.server.port=9443
      - traefik.http.services.portainer-portainer.loadbalancer.server.scheme=https
